---
- name: install iterm2
  homebrew_cask:
    name: iterm2
    state: present

- name: install zsh syntax highlighting
  homebrew:
    name: zsh-syntax-highlighting
    state: latest

- name: install peco
  homebrew:
    name: peco
    state: latest

- name: Clone zsh-peco-history into oh-my-zsh plugins directory
  git:
    repo: "{{ zsh_peco_history_repo }}"
    dest: "{{ omz_custom_dir }}/plugins/zsh-peco-history"
    force: yes

- name: Clone zsh-autosuggestions into oh-my-zsh plugins directory
  git:
    repo: "{{ zsh_autosuggestions_repo }}"
    dest: "{{ omz_custom_dir }}/plugins/zsh-autosuggestions"
    force: yes

- name: Clone zsh-syntax-highlighting into oh-my-zsh plugins directory
  git:
    repo: "{{ zsh_syntax_highlighting_repo }}"
    dest: "{{ omz_custom_dir }}/plugins/zsh-syntax-highlighting"
    force: yes

- name: Clone powerlevel9k into oh-my-zsh themes directory
  git:
    repo: "{{ powerlevel9k_repo }}"
    dest: "{{ omz_custom_dir }}/themes/powerlevel9k"
    force: yes

- name: Clone personal dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ playbook_dir }}/../dotfiles"
    force: yes

- name: chmod dotfiles script +x
  file:
    path: "{{ playbook_dir }}/../dotfiles/dotfiles.sh"
    mode: "0744"

- name: execute dotfiles script
  shell: "{{ playbook_dir }}/../dotfiles/dotfiles.sh"
