---
zsh_peco_history_repo: "https://github.com/jimeh/zsh-peco-history.git"
zsh_autosuggestions_repo: "https://github.com/zsh-users/zsh-autosuggestions"
zsh_syntax_highlighting_repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
powerlevel9k_repo: "https://github.com/bhilburn/powerlevel9k.git"
dotfiles_repo: "git@github.com:elliottnichols/dotfiles.git"
omz_custom_dir: "~/.oh-my-zsh/custom"
