---
- name: Install lshw
  package:
    name: lshw
    state: latest

- name: Install kupfer
  package:
    name: kupfer
    state: latest

- name: Install Silver Searcher
  package:
    name: silversearcher-ag
    state: latest
