---
- name: Add tap caskroom/fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Cask install font-hack-nerd-font
  homebrew_cask:
    name: font-hack-nerd-font
    state: present

  #- name: install powerline patched font
  # shell: "cp '{{ working_dir }}/{{ powerline_fonts_workdir }}/{{ powerline_font_family }}/{{ powerline_font }}' ~/Library/Fonts/"

- debug:
    msg: "**NOTE** Hack Font must be configured in terminal profile"
